---
name: clang-format style check

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    name: clang-format style check
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install dependencies
        # yamllint disable rule:line-length
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key \
          | sudo gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg
          echo "deb [signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/resolute/ llvm-toolchain-resolute-22 main" \
          | sudo tee /etc/apt/sources.list.d/llvm.list && \
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends --no-install-suggests clang-format-22
          sudo update-alternatives --install /usr/bin/clang-format clang-format $(which clang-format-22) 100
          sudo update-alternatives --set clang-format $(update-alternatives --list clang-format | grep clang-format-22)
          # yamllint enable rule:line-length

      - name: Check Tools
        run: |
          make --version
          cmake --version
          clang-format --version

      - name: Style Check
        run: make test/styling
