---

name: CppCheck Lint

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    name: CppCheck Lint
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install tools
        run: |
          sudo snap install cppcheck

      - name: Check Tools
        run: |
          make --version
          cmake --version
          vcpkg --version
          cppcheck --version

      - name: Install dependencies
        run: |
          make dependencies

      - name: Lint
        run: |
          export VCPKG_ROOT=/usr/local/share/vcpkg
          make test/static
